### ISSUE TITLE
Plivo doesn't agree with your program

### ISSUE THREAD

**Issue by johnmudd** [chadselph/smssplit#2]
I use Plivo and Twilio to send SMS. Starting on 6:30am EST 2/15/17, Plivo started encoding some of my texts as Unicode. Texts that previously didn't require Unicode. Texts that Twilio still sends without encoding as Unicode. Here's an example.

    Su receta(s) estan listas para ser recogidas en XXXXXXXX XXXXXXXX. Si tiene alguna pregunta, favor contactar la farmacia al 999-999-9999. ¡Gracias!

I tested this on your website http://chadselph.github.io/smssplit/

According to your program the message uses valid GSM characters and will fit in a single text. I think you're correct but Plivo disagrees. I've been arguing with Plivo for two weeks and they still insist this message must be encoded as Unicode and are charging triple since using Unicode obviously requires three texts. They say the reason they previously only charged for one text was a bug in their system. They fixed the glitch and are now charging triple.

I'm sorry to bother you. But since Plivo insists your web site is invalid I thought I should at least bring this to your attention.

**Comment by johnmudd** [comment]
Update: I just received a reply from Plivo's product manager. They now agree that the message can be encoded as GSM and are working on a fix. Thanks for your web site. It was helpful to prove my point.

**Comment by chadselph** [comment]
Haha... glad the tool was helpful. Obviously there's no guarantees about how any given provider will segment or encode your message. The tool merely shows one strategy: use GSM if possible, otherwise do UCS2. But, there could be reasons to use UCS2 even though GSM is possible. For example, if you're going through an aggregator that is using Latin-1, you might have to switch to UCS-2 for characters in GSM but not Latin-1. It doesn't sound like this was the case with Plivo, it sounds like they just didn't know about GSM character encoding.
