### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by chrisconlon-klaviyo** [chadselph/smssplit#3]
Hey there, thanks for creating this tool, its been super helpful. I'm using your logic to track how many segments are being created (and I'm being charged for) for each message that I send. I had to port it to python though, which I did [here](https://github.com/chrisconlon-klaviyo/sms-toolkit).

Not sure if this is a cool thing to do or not, but I was wondering if you wanted to link to my port in your readme so that other travelers don't have to port it again? No worries if not, just want to save others time.

**Comment by chadselph** [comment]
yeah, sure. although i'm willing to bet if you look hard enough you'd find tons of implementations on github in lots of different languages.

It's funny because the original code (at twilio) was written in Python for our API and then later in Scala for JVM backend services; this was just a visualization I wrote to explain it to some customer support people, but it kinda blew up and they even started sharing it with customers 😱

I should probably have some kind of disclaimer because there's no guarantee your sms provider  (or that some intermediary between them and the handset) will split things the same way

**Comment by chrisconlon-klaviyo** [comment]
Oh boy, I know how that goes. FWIW it was really helpful to me, so thank you. Appreciate the link you added too!
